# Generated by Django 5.0.7 on 2024-08-05 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='مبلغ سهم')),
                ('status', models.CharField(choices=[('onhold', 'در انتظار پرداخت'), ('verified', 'قطعی')], default='onhold', max_length=20, verbose_name='وضعیت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.order')),
            ],
            options={
                'verbose_name': 'سهم دولوپر',
                'verbose_name_plural': 'سهم دولوپر',
            },
        ),
    ]
