# Generated by Django 5.0.7 on 2024-08-05 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش ها'},
        ),
        migrations.AlterModelOptions(
            name='purchaseditem',
            options={'verbose_name': 'کالای سفارشی', 'verbose_name_plural': 'کالاهای سفارشی'},
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='anything_wrong',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='مشکل در سفارش'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالک سفارش'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آخرین تغییر'),
        ),
    ]
