# Generated by Django 5.0.7 on 2024-10-28 22:41

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='عنوان')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن پست')),
                ('is_visible', models.BooleanField(default=True, verbose_name='نمایش دادن در وبلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد پست')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی پست')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پست بلاگ',
                'verbose_name_plural': 'پست بلاگ',
            },
        ),
    ]
