# Generated by Django 5.0.7 on 2024-09-17 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(blank=True, max_length=50, verbose_name='شناسه سبد')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('cost', models.IntegerField(default=0, verbose_name='شیتیل موردنیاز')),
                ('discounts', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('belongs_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='به نام')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد های خرید',
            },
        ),
        migrations.CreateModel(
            name='TakenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='شمار')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس؟')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='کالا')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stack.stack', verbose_name='خرمن')),
            ],
            options={
                'verbose_name': 'کالای داخل سبدخرید',
                'verbose_name_plural': 'کالاهای داخل سبدخرید',
            },
        ),
    ]
