# Generated by Django 5.0.7 on 2024-08-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stack',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد های خرید'},
        ),
        migrations.AlterModelOptions(
            name='takenproduct',
            options={'verbose_name': 'کالای داخل سبدخرید', 'verbose_name_plural': 'کالاهای داخل سبدخرید'},
        ),
    ]
